### ISSUE TITLE
SHA1 symbol can already be defined

### ISSUE THREAD

**Issue by rotoglup** [ETCLabs/EtcPal#61]
While using the [sACN library](https://github.com/ETCLabs/sACN), I have troubles statically linking with an application using OpenSSL :

- OpenSSL defines a `SHA1` function ([part of its `libcrypto`](https://github.com/openssl/openssl/blob/36424806d699233b9a90a3a97fff3011828e2548/crypto/sha/sha1_one.c#L38))
- EtcPal also defines a `SHA1` function (unused, [from an internal use thirdparty lib](https://github.com/ETCLabs/EtcPal/blob/7430eeb2999015ffc1374a2f396e2db869e76799/src/etcpal/thirdparty/sha1.c#L291))

IMHO as `SHA1` is a pretty common name, it would be nice if EtcPal private version has some prefix name to prevent name conflicts using static linking.

**Comment by ChristianReese** [comment]
Hello @rotoglup - thanks for bringing this to our attention. I've put together a merge request for this that's currently in review. I anticipate we'll have new EtcPal and sACN builds for this by tomorrow morning.

**Comment by ChristianReese** [comment]
I've integrated the fix into EtcPal 1.0.0.8 and sACN 3.0.0.16 - closing this issue, but please let us know if additional issues pop up.
